### ISSUE TITLE
on chrome using latest node - does not look right

### ISSUE THREAD

**Issue by mcqueenorama** [codeskyblue/file-server#2]
Looks really nice!

QR icon does not seem to work.

What is the Jacob directory?

<img width="1284" alt="screen shot 2015-10-13 at 8 07 55 am" src="https://cloud.githubusercontent.com/assets/843136/10458836/ac72dad6-7181-11e5-85f7-06b00c72080d.png">

**Comment by codeskyblue** [comment]
please update and use the new version.
